import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";



import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Merriweather, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const jetbrainsMonoJetbrainsMono = JetBrains_Mono({subsets:['latin','latin-ext','cyrillic','cyrillic-ext','greek','vietnamese'],weight:['100','200','300','400','500','600','700','800'],variable:'--font-jetbrains-mono'});

const merriweatherMerriweather = Merriweather({subsets:['cyrillic','cyrillic-ext','latin','latin-ext','vietnamese'],weight:['300','400','500','600','700','800','900'],variable:'--font-merriweather'});

const interInter = Inter({subsets:['latin','latin-ext','cyrillic','cyrillic-ext','greek','greek-ext','vietnamese'],weight:['100','200','300','400','500','600','700','800','900'],variable:'--font-inter'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("antialiased", geistSans.variable, geistMono.variable, interInter.variable, merriweatherMerriweather.variable, jetbrainsMonoJetbrainsMono.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-screen">
        <SidebarProvider className="min-h-screen">
          <AppSidebar />

          <main className="flex min-h-screen flex-1 flex-col">
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
